/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

struct OutputInfo *
performaddition_1_svc(struct InputInfo *argp, struct svc_req *rqstp)
{
	static struct OutputInfo  result;
	int i =1;
	int fact=1;

	/*
	 * insert server code here
	 */
	
      while(i<=argp->num1){
      fact=fact*i;
      i++;
  }	
result.result=fact;
	printf("Hello from Server");

	return &result;
}
