/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "fact.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct OutputInfo *
performaddition_1(struct InputInfo *argp, CLIENT *clnt)
{
	static struct OutputInfo clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, performAddition,
		(xdrproc_t) xdr_InputInfo, (caddr_t) argp,
		(xdrproc_t) xdr_OutputInfo, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
