/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fact.h"

bool_t
xdr_InputInfo (XDR *xdrs, InputInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num1))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_OutputInfo (XDR *xdrs, OutputInfo *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
