/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"
/*Display function */


void display_result(int a ,char * type){
	printf("%s is %d\n",type,a);
}

void
rpcprogram_1(char *host,int a)//added 
{
	CLIENT *clnt;
	struct OutputInfo  *result_1;
	struct InputInfo  performaddition_1_arg;
	performaddition_1_arg.num1=a; // added 

#ifndef	DEBUG
	clnt = clnt_create (host, RPCPROGRAM, FACTVERSION, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = performaddition_1(&performaddition_1_arg, clnt);
	if (result_1 == (struct OutputInfo *) NULL) {
		clnt_perror (clnt, "call failed");
	}
else{
		display_result(result_1->result,"Factorial"); //added 
		
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
int a;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	/* added */
	printf("\nEnter  num : ");
	scanf("%d",&a);
	rpcprogram_1 (host,a);


exit (0);
}
